name: ci-verificar-codigo

on:
  push:
    branches: ['main']

jobs:
  integracion-continua:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v3

      - name: Prueba de existencia de archivos
        run: |
          if [ -f "vistas/index.html" ] && [ -f "css/styles.css" ]; then
            echo "Éxito: Los archivos index.html y styles.css existen en sus carpetas."
          else
            echo "Error: Faltan archivos base."
            exit 1
          fi

  despliegue-continuo:
    needs: integracion-continua
    runs-on: ubuntu-latest
 
    steps:
      - name: Simulación de Despliegue
        run: |
          echo "Compilando activos y preparando servidor..."
          echo "Artefactos listos para el despliegue en el entorno de Staging"